config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Home', 'action' => 'residentIndex']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Newsletter.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Newsletter Entity
 *
 * @property int $id
 * @property string $file_name
 * @property string $category
 * @property string $Hyperlink
 * @property \Cake\I18n\FrozenDate $date_published
 */
class Newsletter extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'file_name' => true,
        'category' => true,
        'archived' => true,
        'date_published' => true,
        'display_field' => true,
        'Hyperlink' => true

    ];

    // this function will return the url of the newsletter file
    protected function _getNewsletterFileUrl(){
        return \Cake\Routing\Router::url("/files/Newsletters/file_name/{$this->file_name}");
    }

    // this function will return the full category name
    protected function _getCategoryName(){
        if($this->category == 'C'){
            return 'Committee';
        }
        else if ($this->category == 'L'){
            return 'Lendlease';
        }
        else{
            return '';
        }
    }
}

src/Model/Table/NewslettersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Newsletters Model
 *
 * @method \App\Model\Entity\Newsletter get($primaryKey, $options = [])
 * @method \App\Model\Entity\Newsletter newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Newsletter[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Newsletter|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Newsletter patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Newsletter[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Newsletter findOrCreate($search, callable $callback = null, $options = [])
 */
class NewslettersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('newsletters');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
        $this->addBehavior('Josegonzalez/Upload.Upload', [
            // You can configure as many upload fields as possible,
            // where the pattern is `field` => `config`
            //
            // Keep in mind that while this plugin does not have any limits in terms of
            // number of files uploaded per request, you should keep this down in order
            // to decrease the ability of your users to block other requests.
            'file_name'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('file_name', 'create')
            ->add('file_name', [
                'validExtension' => [
                    'rule' => ['extension',['pdf']], // default  ['gif', 'jpeg', 'png', 'jpg']
                    'message' => ('Only PDF files are allowed to be uploaded.')
                ]
            ])
            ->allowEmpty('file_name','update');


        $validator
            ->scalar('category')
            ->requirePresence('category', 'create')
            ->notEmpty('category');

        $validator
            ->date('date_published')
            ->requirePresence('date_published', 'create')
            ->notEmpty('date_published');

        $validator
            ->scalar('Hyperlink')
            ->maxLength('Hyperlink', 255)
            ->allowEmpty('Hyperlink');



        return $validator;
    }
}

src/Controller/NewslettersController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\I18n\Time;

/**
 * Newsletters Controller
 *
 * @property \App\Model\Table\NewslettersTable $Newsletters
 *
 * @method \App\Model\Entity\Newsletter[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class NewslettersController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->loadModel('Residents');
    }

    public function isAdmin(){
        //get the user's ID
        $userID = $this->Auth->user('id');

        //get the role name of this user
        $roleQuery = $this->Residents->find();
        $query = $roleQuery->select([
            'role' => 'Roles.name',
        ])
            ->innerJoinWith('Roles')
            ->where(['Residents.id' => $userID]);

        //get the role name
        $role = $query->first();

        //apply admin layout if the user is an admin
        if($role['role'] == 'ADMIN'){
            return TRUE;
        }
        else{
            return FALSE;
        }
    }

    public function isResident(){
        //get the user's ID
        $userID = $this->Auth->user('id');

        //get the role name of this user
        $roleQuery = $this->Residents->find();
        $query = $roleQuery->select([
            'role' => 'Roles.name',
        ])
            ->innerJoinWith('Roles')
            ->where(['Residents.id' => $userID]);

        if($query->count() == 0){
            return TRUE;
        }
        else{
            return FALSE;
        }
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        if($this->isResident()) {
            $this->redirect(['controller' => 'Residents', 'action' => 'no_access']);
        }
        elseif ($this->isAdmin()){
            $this->layout = 'admin';
        }
        else{
            $this->layout = 'default';
            $this->redirect(['controller' => 'Residents', 'action' => 'current_committee']);
        }

        $newsletters = $this->Newsletters->find('all')->where(['Newsletters.archived' => false])->contain([]);

        $this->set(compact('newsletters'));
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        if($this->isResident()) {
            $this->redirect(['controller' => 'Residents', 'action' => 'no_access']);
        }
        elseif ($this->isAdmin()){
            $this->layout = 'admin';
        }
        else{
            $this->layout = 'default';
            $this->redirect(['controller' => 'Residents', 'action' => 'current_committee']);
        }

        $newsletter = $this->Newsletters->newEntity();
        if ($this->request->is('post')) {
//            debug($this->request->getData());
//            debug($this->request->getUploadedFiles());

            //Convert date from the form to TimeObject
            $date_published_raw = $this->request->getData('date_published');
            $date_published = Time::createFromFormat("d-m-Y", $date_published_raw);

            //Patch the date correctly (since patchEntity will not accept d-m-Y format date)
            $newsletter = $this->Newsletters->patchEntity($newsletter, $this->request->getData());
            $newsletter->date_published = $date_published;


            if ($this->Newsletters->save($newsletter)) {
                $this->Flash->success(__('The newsletter has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The newsletter could not be saved. Please, try again.'));
        }
        $this->set(compact('newsletter'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Newsletter id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        if($this->isResident()) {
            $this->redirect(['controller' => 'Residents', 'action' => 'no_access']);
        }
        elseif ($this->isAdmin()){
            $this->layout = 'admin';
        }
        else{
            $this->layout = 'default';
            $this->redirect(['controller' => 'Residents', 'action' => 'current_committee']);
        }

        $newsletter = $this->Newsletters->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {

            //Convert date from the form to TimeObject
            $date_published_raw = $this->request->getData('date_published');
            $date_published = Time::createFromFormat("d-m-Y", $date_published_raw);

            //Patch the date correctly (since patchEntity will not accept d-m-Y format date)
            $newsletter = $this->Newsletters->patchEntity($newsletter, $this->request->getData());
            $newsletter->date_published = $date_published;

            if ($this->Newsletters->save($newsletter)) {
                $this->Flash->success(__('The newsletter has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The newsletter could not be saved. Please, try again.'));
        }
        $this->set(compact('newsletter'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Newsletter id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $newsletter = $this->Newsletters->get($id);
        if ($this->Newsletters->delete($newsletter)) {
            $this->Flash->success(__('The newsletter has been deleted.'));
        } else {
            $this->Flash->error(__('The newsletter could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'archive-index']);
    }

    public function archive($id = null){

        $newsletter = $this->Newsletters->get($id);
        $newsletter->archived = true;

        if ($this->Newsletters->save($newsletter)){
            $this->Flash->success(__('This newsletter has been archived.'));

            return $this->redirect(['action' => 'index']);

        }
        $this->Flash->error(__('Unable to archive this newsletter.'));
    }

    public function restore($id = null)
    {
        $newsletter = $this->Newsletters->get($id);
        $newsletter->archived = false;

        if ($this->Newsletters->save($newsletter)) {
            $this->Flash->success(__('This newsletter has been restored.'));

            return $this->redirect(['action' => 'archiveIndex']);
        }
        $this->Flash->error(__('Unable to restore this newsletter.'));
    }


    public function archiveIndex(){
        if($this->isResident()) {
            $this->redirect(['controller' => 'Residents', 'action' => 'no_access']);
        }
        elseif ($this->isAdmin()){
            $this->layout = 'admin';
        }
        else{
            $this->layout = 'default';
            $this->redirect(['controller' => 'Residents', 'action' => 'current_committee']);
        }

        $archivedNewsletters = TableRegistry::get('Newsletters')->find('all')->where(['Newsletters.archived' => true])->contain([]);
        $this->set('archivedNewsletters', $archivedNewsletters);
    }

    public function residentIndex(){
        $this->layout = 'resident';
        $newsletters = $this->Newsletters->find('all')->where(['Newsletters.archived' => false])->contain([]);
        $this->set(compact('newsletters'));
    }


}

src/Template/Newsletters/archive_index.ctp
<?php
/**
* @var \App\View\AppView $this
* @var \App\Model\Entity\Newsletter[]|\Cake\Collection\CollectionInterface $newsletters
*/
?>





<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Archived Newsletters</h1>


            <div class="card mb-4 w-125">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Archived files table</div>
                <div class="card-body w-100">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Newletters</th>
                                <th>Category</th>
                                <th>Find more details here</th>
                                <th>Date Published</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($archivedNewsletters as $newsletter): ?>
                                <tr>
                                    <td><?= $this->Html->link($newsletter->display_field,"/webroot/files/Newsletters/file_name/".$newsletter->file_name, ['target'=>'_blank']) ?></td>
                                    <td><?= h($newsletter->category_name) ?></td>
                                    <td><?= h($newsletter->Hyperlink) ?></td>
                                    <td><?= h($newsletter->date_published->format("d M, Y")) ?></td>
                                    <td class="actions" align="center">
                                        <button type ="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmModal-<?= $newsletter->id?>">Restore</button>

                                        <div class="modal fade" id="confirmModal-<?= $newsletter->id?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Are you sure you want to restore this newsletter - <?= $newsletter->file_name?>?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <?= $this->Form->postLink(__('Yes'), ['action' => 'restore', $newsletter->id], array('style' => 'color: black;','class'=>'btn btn-light')) ?>
                                                        <button type="button" class="btn btn-dark" data-dismiss="modal">No</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <button type ="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmModal<?=$newsletter->id ?>"">Delete</button>

                                        <div class="modal fade" id="confirmModal<?=$newsletter->id ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Are you sure you want to delete this file - <?= $newsletter->file_name?>?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <?= $this->Form->postLink(__('Yes'), ['action' => 'delete', $newsletter->id], array('style' => 'color: black;','class'=>'btn btn-light')) ?>
                                                        <button type="button" class="btn btn-dark" data-dismiss="modal">No</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

src/Template/Newsletters/index.ctp
<?php
/**
* @var \App\View\AppView $this
* @var \App\Model\Entity\Newsletter[]|\Cake\Collection\CollectionInterface $newsletters
*/
?>



<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Newsletters page</h1>

            <div class="mt-4 mb-4" align="right">
                <?= $this->Html->link("Add Newsletter", ['action' => 'add'], array('style' => 'color:white', 'class'=>'btn btn-primary', 'style'=> 'width: 180px')) ?>
            </div>
            <div class="card mb-4 w-125">
                <div class="card-header"><i class="fas fa-table mr-1"></i>Newsletters table</div>
                <div class="card-body w-100">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Newsletter</th>
                                <th>Category</th>
                                <th>Find more details here</th>
                                <th>Date Published</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($newsletters as $newsletter): ?>
                                <tr>
                                    <td><?= $this->Html->link($newsletter->display_field,"/webroot/files/Newsletters/file_name/".$newsletter->file_name,['target' =>'_blank']) ?></td>
                                    <td><?= h($newsletter->category_name) ?></td>
                                    <td><?= h($newsletter->Hyperlink) ?></td>
                                    <td><?= h($newsletter->date_published->format("d M, Y")) ?></td>
                                    <td class="actions" width="50%" align="center">
                                        <a class="btn btn-primary mb-1" href="
                                        <?php echo $this->Url->build([
                                            "controller" => "Newsletters",
                                            "action" => "edit",
                                            $newsletter->id
                                        ]);?>">Edit</a>
                                        <button type ="button" class="btn btn-primary mb-1" data-toggle="modal" data-target="#confirmModal-<?=$newsletter->id ?>" data-id="<?php echo $newsletter->id?>" id="<?php echo $newsletter->id ?>">Archive</button>

                                        <div class="modal fade" id="confirmModal-<?=$newsletter->id ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Confirm</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Are you sure you want to archive this newsletter - <?php echo $newsletter->file_name?>?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <?= $this->Form->postLink(__('Yes', '#'), ['action' => 'archive', $newsletter->id], array('style' => 'color: black;','class'=>'btn btn-light')) ?>
                                                        <button type="button" class="btn btn-dark" data-dismiss="modal">No</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </td>
                                </tr>
                            <?php endforeach; ?>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

src/Template/Newsletters/resident_index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Newsletter[]|\Cake\Collection\CollectionInterface $newsletters
 */
?>



<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Noticeboard
<!--        <small>Newsletters</small>-->
    </h1>

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a>Noticeboard</a>
        </li>
        <li class="breadcrumb-item active">Newsletters</li>
    </ol>

    <div align="center">
        <b><?= $this->Html->link(__('Newsletters'), ['controller' => 'Newsletters', 'action' => 'resident_index'], array('class' => 'btn btn-secondary mt-2')) ?></b>
        <?= $this->Html->link(__('Minutes'), ['controller' => 'Minutes', 'action' => 'resident_index'], array('class' => 'btn btn-primary mt-2 ml-2')) ?>
        <?= $this->Html->link(__('Calendars'), ['controller' => 'Calendars', 'action' => 'resident_index'], array('class' => 'btn btn-primary mt-2 ml-2')) ?>
        <?= $this->Html->link(__('Food Menus'), ['controller' => 'Menus', 'action' => 'resident_index'], array('class' => 'btn btn-primary mt-2 ml-2')) ?>
        <?= $this->Html->link(__('Others'), ['controller' => 'Miscellaneous', 'action' => 'resident_index'], array('class' => 'btn btn-primary mt-2 ml-2')) ?>
    </div>

    <div class="alert alert-warning mt-4" role="alert">
        <b>Note</b> : By clicking on a file, a PDF document will be opened in a new tab. When you are done reading the PDF document simply close the tab down, not the window.
    </div>


    <div class="table-responsive">
        <div class="newsletters index large-9 medium-8 columns content">
            <table class="table table-bordered" id="datatable">
                <thead>
                <tr>
                    <th scope="col" style="color:#c507ac">Newsletters</th>
                    <th scope="col" style="color:#c507ac">Category</th>
                    <th scope="col" style="color:#c507ac">More information</th>
                    <th scope="col" style="color:#c507ac">Date Published</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($newsletters as $newsletter): ?>
                    <tr>
                        <td><?= $this->Html->link($newsletter->display_field, "/webroot/files/Newsletters/file_name/".$newsletter->file_name,['target' =>'_blank']) ?></td>
                        <td><?= h($newsletter->category_name) ?></td>
                        <td><?php if (!empty($newsletter->Hyperlink)){?>

                            <a href=" <?php echo $hyperlink= ($newsletter->Hyperlink)?>" target="_blank" style="color: #961982">Click here for more details</a>

                        <?php }?></td>
                        <td data-order="<?= h($newsletter->date_published->format("Y/m/d")) ?>" data-sort="<?= h($newsletter->date_published->format("Y/m/d")) ?>">
                            <?= h($newsletter->date_published->format("d M, Y")) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>


</div>